{
  "name": "education-jobs-dashboard",
  "services": [
    {
      "name": "web",
      "source_dir": "/",
      "github": {
        "repo": "yaro360/EducationEdJoin",
        "branch": "main"
      },
      "run_command": "gunicorn app:app",
      "environment_slug": "python",
      "instance_count": 1,
      "instance_size_slug": "basic-xxs",
      "http_port": 8080,
      "routes": [
        {
          "path": "/"
        }
      ],
      "envs": [
        {
          "key": "FLASK_ENV",
          "value": "production"
        },
        {
          "key": "SECRET_KEY",
          "value": "your-super-secret-key-change-this-in-production"
        }
      ]
    }
  ],
  "static_sites": [],
  "workers": [],
  "jobs": [
    {
      "name": "scraper",
      "source_dir": "/",
      "github": {
        "repo": "yaro360/EducationEdJoin",
        "branch": "main"
      },
      "run_command": "python3 production_scraper.py",
      "environment_slug": "python",
      "instance_count": 1,
      "instance_size_slug": "basic-xxs",
      "envs": [
        {
          "key": "FLASK_ENV",
          "value": "production"
        }
      ]
    }
  ]
}